stages:
  - build
  - deploy
  - test #test suite automation run stage

playwrighttests:
  stage: test
  image: mcr.microsoft.com/playwright:latest #official playwright image
  script:
    - npm install ci
    - npm install -D @playwright/test
    - npm ci
    - npx playwright test
  artifacts:
    paths: #assuming deafult playwright artifacts paths
      - ./playwright-report/
      - ./Screenshot/
      - test-results/
      - results.xml
    when: always
    expire_in: 4 days
    reports:
      junit: results.xml #artifacts will purged after 4 days of test run
