stages:
  - build
  - deploy
  - test

playwrighttests:
  stage: test
  image: mcr.microsoft.com/playwright:latest
  script:
    - npm ci
    - npm install -D @playwright/test
    - npx playwright install
    - npx playwright test
  artifacts:
    paths:
      - ./playwright-report/
      - ./Screenshot/
      - test-results/
      - results.xml
    when: always
    expire_in: 4 days
    reports:
      junit: results.xml
